---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:  
    - name: Fix ownership for folder  clickhouse
      become: true
      command: chown -R clickhouse:clickhouse /var/lib/clickhouse
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks: 
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name: "{{ clickhouse_prerequisites }}"
      tags: prerequisites
    - name: Add apt key from keyserver by id
      become: true
      ansible.builtin.apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80 
        id: 8919F6BD2B48D754      
      tags: prerequisites
    - name: Add official repo for clickhouse server and clickhouse client
      become: true
      command: "echo \"deb https://packages.clickhouse.com/deb stable main\">>/etc/apt/sources.list.d/clickhouse.list"      
      tags: prerequisites
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:  
        name: "{{ clickhouse_packages}}" 
      notify:
        - Fix ownership for folder  clickhouse 
        - Start clickhouse service  
      tags: clickhouse
    - name: Flush handlers
      meta: flush_handlers 
      tags: clickhouse
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q '{{ clickhouse_query }}'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0 
      tags: clickhouse
